// Bundles beautiful-mermaid's ASCII path (no elkjs, no DOM) into one ESM file the
// hooks module imports by relative path: hooks modules run with no Node and cannot
// resolve bare specifiers. Run from the plugin folder: npm install && npm run build:vendor
import { build } from 'esbuild'
import { readFileSync, statSync } from 'node:fs'
import { PATCHES } from './patches.mjs'

const OUT = 'hooks/vendor/mermaid-ascii.js'
const LIMIT = 1024 * 1024

const patched = {
  name: 'beautiful-mermaid-patches',
  setup(api) {
    api.onLoad({ filter: /beautiful-mermaid\/src\/ascii\/[\w-]+\.ts$/ }, args => {
      let source = readFileSync(args.path, 'utf8')
      for (const patch of PATCHES) {
        if (!patch.file.test(args.path)) continue
        if (source.split(patch.find).length !== 2) throw new Error(`${args.path}: patch anchor changed upstream; refresh scripts/patches.mjs`)
        source = source.replace(patch.find, patch.replace)
      }
      return { contents: source, loader: 'ts' }
    })
  },
}

await build({
  stdin: {
    contents: "export { renderMermaidAscii } from './node_modules/beautiful-mermaid/src/ascii/index.ts'",
    resolveDir: '.',
    loader: 'ts',
  },
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2023',
  outfile: OUT,
  legalComments: 'none',
  plugins: [patched],
  banner: { js: '// Generated by scripts/build-vendor.mjs from beautiful-mermaid (MIT, see hooks/vendor/LICENSE) with scripts/patches.mjs applied. Do not edit.' },
})

const size = statSync(OUT).size
if (size >= LIMIT) throw new Error(`${OUT} is ${size} bytes; Claude Code does not read a module file over 1 MiB`)
console.log(`${OUT}: ${size} bytes`)
