// Bundles the two renderers into ESM files the hooks module imports by relative path:
// hooks modules run with no Node and cannot resolve bare specifiers, and Claude Code
// does not read a module file over 1 MiB.
// - beautiful-mermaid's ASCII path (no elkjs, no DOM) into hooks/vendor/mermaid-ascii.js
// - MathJax's TeX-to-SVG path (scripts/math-entry.mjs) into hooks/vendor/math/, split
//   into chunks each under the limit; mathjax.js is the file the hooks import
// Run from the plugin folder: npm install && npm run build:vendor
import { build } from 'esbuild'
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'
import { PATCHES } from './patches.mjs'

const OUT = 'hooks/vendor/mermaid-ascii.js'
const LIMIT = 1024 * 1024

const applied = new Set()

const patched = {
  name: 'beautiful-mermaid-patches',
  setup(api) {
    api.onLoad({ filter: /beautiful-mermaid\/src\/.+\.ts$/ }, args => {
      let source = readFileSync(args.path, 'utf8')
      for (const patch of PATCHES) {
        if (!patch.file.test(args.path)) continue
        if (source.split(patch.find).length !== 2) throw new Error(`${args.path}: patch anchor changed upstream; refresh scripts/patches.mjs`)
        source = source.replace(patch.find, () => patch.replace)
        applied.add(patch)
      }
      return { contents: source, loader: 'ts' }
    })
  },
}

const { outputFiles } = await build({
  stdin: {
    contents: "export { renderMermaidAscii } from './node_modules/beautiful-mermaid/src/ascii/index.ts'",
    resolveDir: '.',
    loader: 'ts',
  },
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2023',
  outfile: OUT,
  legalComments: 'none',
  plugins: [patched],
  write: false,
  banner: { js: '// Generated by scripts/build-vendor.mjs from beautiful-mermaid (MIT, see hooks/vendor/LICENSE) with scripts/patches.mjs applied. Do not edit.' },
})

const missed = PATCHES.filter(patch => !applied.has(patch))
if (missed.length > 0) throw new Error(`patch target never loaded: ${missed.map(patch => patch.file).join(', ')}; refresh scripts/patches.mjs`)

const [bundle] = outputFiles
const size = bundle.contents.byteLength
if (size >= LIMIT) throw new Error(`${OUT} is ${size} bytes; Claude Code does not read a module file over 1 MiB`)
writeFileSync(OUT, bundle.contents)
console.log(`${OUT}: ${size} bytes`)

// MathJax: one entry for the surface the hooks import, and entries for the TeX input
// and the SVG font tables, so --splitting cuts the font data into chunks of their own.
// Only the surface entry and the chunks it reaches are written; the other entries
// exist to shape the split and are left out.
const MATH_OUT = 'hooks/vendor/math'
const FONTS = 'node_modules/mathjax-full/js/output/svg/fonts/tex'
const math = await build({
  entryPoints: {
    mathjax: 'scripts/math-entry.mjs',
    'split-input': 'node_modules/mathjax-full/js/input/tex.js',
    'split-normal': `${FONTS}/normal.js`,
    'split-fonts': `${FONTS}.js`,
  },
  bundle: true,
  splitting: true,
  minify: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2023',
  outdir: MATH_OUT,
  legalComments: 'none',
  write: false,
  banner: { js: '// Generated by scripts/build-vendor.mjs from mathjax-full (Apache-2.0, see hooks/vendor/LICENSE-mathjax). Do not edit.' },
})

const byName = new Map(math.outputFiles.map(file => [basename(file.path), file]))
const reached = new Set()
const reach = name => {
  if (reached.has(name)) return
  const file = byName.get(name)
  if (!file) throw new Error(`${MATH_OUT}/${name} imported but not built`)
  reached.add(name)
  if (/\bimport\s*\(/.test(file.text)) throw new Error(`${MATH_OUT}/${name} imports dynamically`)
  for (const [, dep] of file.text.matchAll(/(?:from|import)\s*"\.\/([^"]+)"/g)) reach(dep)
}
reach('mathjax.js')
for (const name of reached) {
  const size = byName.get(name).contents.byteLength
  if (size >= LIMIT) throw new Error(`${MATH_OUT}/${name} is ${size} bytes; Claude Code does not read a module file over 1 MiB`)
}
mkdirSync(MATH_OUT, { recursive: true })
for (const name of readdirSync(MATH_OUT)) if (name.endsWith('.js')) rmSync(join(MATH_OUT, name))
for (const name of [...reached].sort()) {
  const file = byName.get(name)
  writeFileSync(join(MATH_OUT, name), file.contents)
  console.log(`${MATH_OUT}/${name}: ${file.contents.byteLength} bytes`)
}
